FROM nginx:1.20.0
ARG TARGETPLATFORM

RUN apt-get update && apt-get install -y awscli cron curl netcat procps wget
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then curl https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb -o session-manager-plugin.deb; fi
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then curl https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb -o session-manager-plugin.deb; fi

RUN dpkg -i session-manager-plugin.deb

WORKDIR /root

RUN curl https://secure.eicar.org/eicar.com -o eicarfile 
RUN chmod +x eicarfile

COPY files/scripts/40-execute-cron.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/*

COPY files/scripts/make_*.sh .
RUN chmod +x *.sh

COPY files/cron/ /etc/cron.d/
RUN chmod 644 /etc/cron.d/*
RUN crontab /etc/cron.d/havok

RUN rm -R /usr/share/nginx/html/*
RUN rm /etc/nginx/conf.d/default.conf

COPY files/nginx/conf /etc/nginx/conf.d/
COPY files/www/ /usr/share/nginx/html

COPY files/wallet/config.json .
COPY files/mongodb/mongo_secret.txt .
COPY files/userdata/UserData.txt .

COPY files/secrets/fake-hr.admin.dem .azure/accessToken.json

EXPOSE 8080
